name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./emergencyCall/pom.xml
          mvn clean package -f ./dispatch/pom.xml
          mvn clean package -f ./hospital/pom.xml

      - name: Docker Build and push for EmergencyCall
        uses: docker/build-push-action@v4
        with:
          context: ./emergencyCall
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/emergencycall:latest
            ghcr.io/${{ github.repository }}/emergencycall:${{ github.ref_name }}
            
      - name: Docker Build and push for Dispatch
        uses: docker/build-push-action@v4
        with:
          context: ./dispatch
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dispatch:latest
            ghcr.io/${{ github.repository }}/dispatch:${{ github.ref_name }}
            
      - name: Docker Build and push for Hospital
        uses: docker/build-push-action@v4
        with:
          context: ./hospital
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hospital:latest
            ghcr.io/${{ github.repository }}/hospital:${{ github.ref_name }}
            
