server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: emergencyCall
          uri: http://localhost:8082
          predicates:
            - Path=/calls/**, 
        - id: dispatch
          uri: http://localhost:8083
          predicates:
            - Path=/dispatches/**, 
        - id: hospital
          uri: http://localhost:8084
          predicates:
            - Path=/hospitals/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: emergencyCall
          uri: http://emergencyCall:8080
          predicates:
            - Path=/calls/**, 
        - id: dispatch
          uri: http://dispatch:8080
          predicates:
            - Path=/dispatches/**, 
        - id: hospital
          uri: http://hospital:8080
          predicates:
            - Path=/hospitals/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
